run:
	python3 main.py
setup: requirements.txt
	pip3 install -r requirements.txt
	sudo apt-get update
	sudo apt-get install python3-tk
	sudo apt-get install python3-pil.imagetk
	sudo apt-get install python3-pil.image
clean:
	rm -rf __pycache__

